### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by SP1966** [ellipsesynergie/api-response#12]
In the Laravel/Lumen example for the Master branch it says:

use EllipseSynergie\ApiResponse\Contracts\Response;

Should be:

use EllipseSynergie\ApiResponse\Laravel\Response;

Also 

//Custom meta
        $meta = [
            'readers' = $book->readers
        ];

Should be:

//Custom meta
        $meta = [
            'readers' => $book->readers
        ];

**Comment by maximebeaudoin** [comment]
The Lumen service provider https://github.com/ellipsesynergie/api-response/blob/master/src/Laravel/LumenServiceProvider.php bind the interface to `EllipseSynergie\ApiResponse\Laravel\Response`. You MUST inject `EllipseSynergie\ApiResponse\Contracts\Response`.
