### ISSUE TITLE
Wondering how to return null / object on links json output

### ISSUE THREAD

**Issue by ChaosPower** [ellipsesynergie/api-response#13]
Hi ellipsesynergie,

Would like to know how to return links

from

```
"pagination": {
"total": 25,
"count": 25,
"per_page": 80,
"current_page": 1,
"total_pages": 1,
"links": [ ]
}
```

to blank object

```
"pagination": {
"total": 25,
"count": 25,
"per_page": 80,
"current_page": 1,
"total_pages": 1,
"links": {}
}

```

**Comment by maximebeaudoin** [comment]
@ChaosPower This package use the default serializer `League\Fractal\Serializer\ArraySerializer`from fractal. If you want to create a custom serializer, you can follow http://fractal.thephpleague.com/serializers and register your serializer into a custom service provider. You can take a look at https://github.com/ellipsesynergie/api-response/blob/master/src/Laravel/ResponseServiceProvider.php#L44 for more details.
