### ISSUE TITLE
Does this handle exceptions?

### ISSUE THREAD

**Issue by malhal** [ellipsesynergie/api-response#15]
E.g. if I get an QueryException or a ModelNotFoundException will this library also give a json response? Or do I still need to make my own handler and in there return the errorNotFound etc. Thanks.

**Comment by dominicmartineau** [comment]
@malhal You can use `error*` methods 

```PHP
return $this->response->errorForbidden();
return $this->response->errorInternalError();
return $this->response->errorNotFound();
return $this->response->errorUnauthorized();
return $this->response->errorWrongArgs();
return $this->response->errorGone();
return $this->response->errorMethodNotAllowed();
return $this->response->errorUnwillingToProcess();
```

or `withError()` for custom error

```PHP
return $this->response->setStatusCode(404)->withError($message, $code);
```

These methods will return a JSON like this one (https://github.com/ellipsesynergie/api-response#error):

```JSON
{
    "error": {
        "code": "GEN-NOT-FOUND",
        "http_code": 404,
        "message": "Book Not Found"
    }
}
```

**Comment by malhal** [comment]
Thanks but I mean for errors out of my control. Like if my code exceptions. Do I need to try/catch and then call withError?

**Comment by dominicmartineau** [comment]
@malhal Yup, you need to do some kind of try/catch and then call `->withError()`. If you're are using Laravel 5, you should use the `render()` method from the exception handler (http://laravel.com/docs/5.0/errors#handling-errors).

**Comment by malhal** [comment]
Thanks Render report() looks the right place to catch all errors from anywhere in the stack. I guess my next question is can I put something in the Handler that will give the right error response in your list above automatically depending on the exception? E.g. if its a ModelNotiFoundException rather than catch it and call errorNotFound and have that for every single exception type is there a way to get that automatically?

**Comment by dominicmartineau** [comment]
@malhal Here's what we do:

```PHP
public function render($request, Exception $e)
{
        // Catch validator exception
        if ($e instanceof ValidatorException) {
            return response()->api()->errorWrongArgsValidator($e->getValidator());
        }

        // Catch model not found exception
        else if ($e instanceof ModelNotFoundException) {
            return response()->api()->errorNotFound();
        }

        // etc ...
}
```

**Comment by malhal** [comment]
Thanks hopefully this will make it into the library some day. On my own I'd be worried I covered all possible exceptions.

**Comment by dominicmartineau** [comment]
@malhal You could at least return a default error...

**Comment by maximebeaudoin** [comment]
@malhal I understand your concern. Unfortunatly, this is not the reponsability of this package to catch framework or custom exception. 

We want to keep this package simple as possible and the most important, completly framework agnostic.

However, we could probably add some documentation for that kind of stuff.


By the way, you can add this to your handler for laravel default routing exception
```php
// Catch not found
if ($e instanceof \Symfony\Component\HttpKernel\Exception\NotFoundHttpException) {
    return response()->api()->errorNotFound('End point not available');
};

// Catch method not allowed
if ($e instanceof \Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException) {
   return response()->api()->errorMethodNotAllowed();
}
```
