### ISSUE TITLE
Example of Response Class which does not include Laravel Response Factory

### ISSUE THREAD

**Issue by bryantAXS** [ellipsesynergie/api-response#16]
Can you provide an example of what that withArray method needs to return on the response class? It looks like the Laravel Response class you reference in the docs, uses the Response Contract from Laravel5, but that has quite a bit of non-vanilla php within it. Here is what I have, but it's not returning anything currently

```
use EllipseSynergie\ApiResponse\AbstractResponse as AbstractResponse;

class ApiResponse extends AbstractResponse{

    /**
     * @param array $array
     * @param array $headers
     * @return ResponseFactory
     */
    public function withArray(array $array, array $headers = array())
    {

      return json_encode($array);

    }

}
```

**Comment by maximebeaudoin** [comment]
@bryantAXS You implemention seems correct.

You should use it like this

```php
// Instantiate the fractal manager
$manager = new \League\Fractal\Manager;

// Set the request scope if you need include data
$manager->parseIncludes(explode(',', $_GET['include']));

// Instantiate the response object, replace the class name by your custom class
$response = new \ApiResponse($manager);

//Echo the transformer response
echo $response->withItem($book, new BookTransformer);
```

Take a look at your transformer if you return data properly. For more details about Transformer, go to fractal website http://fractal.thephpleague.com/

**Comment by bryantAXS** [comment]
The biggest problem is that the withArray method utilizes Laravel's Response class, which has methods that return the correct headers and spit back the JSON response. The way I was doing it didn't include the headers, which I suppose I didn't necessarily need, but wanted anyway. I ended up grabbing the Symphony Response class (which laravel's Response class extends) and just using that.

Thanks!

**Comment by maximebeaudoin** [comment]
@bryantAXS Of course, you need to use some kind of HTTP response implementation from some package or framework to return response to HTTP client.
