### ISSUE TITLE
Server headers blocked

### ISSUE THREAD

**Issue by grcasanova** [ellipsesynergie/api-response#17]
Hi,
I would like to point out that, with error responses server defined headers are not sent.
For example, in my case I use nginx with this configuration (only headers part)
<code>
add_header X-Frame-Options SAMEORIGIN;</code><br><code>
add_header X-Content-Type-Options nosniff;</code><br><code>
add_header X-XSS-Protection "1; mode=block";
</code>

If I use <code>errorNotFound()</code> (or similar error-reporting methods) the headers are not present, both testing from local development server and from online virtual machine.

**Comment by maximebeaudoin** [comment]
@grcasanova I assume you use Laravel 5.0. I don't know if it's related to laravel response system or nginx handling error when you return a HTTP code 4** or 5** but the header will be erase. 

It's not a behaviour related to this package.

**Comment by grcasanova** [comment]
Ok, I will take a look at Nginx docs. thanks

**Comment by osteel** [comment]
@grcasanova This has to do with Nginx. `add_header` will have no effect with errors. [As per the doc](http://nginx.org/en/docs/http/ngx_http_headers_module.html):

> Adds the specified field to a response header provided that the response code equals 200, 201, 204, 206, 301, 302, 303, 304, or 307.

You want to use `more_set_headers` instead, which can be installed easily with the [nginx-extras package](https://packages.debian.org/sid/nginx-extras).

You'll find more details in the [article I wrote on the subject](http://blog.osteel.me/posts/2015/07/19/handling-cors-with-nginx.html).

**Comment by maximebeaudoin** [comment]
Thank you @osteel for the hint !

**Comment by grcasanova** [comment]
@osteel thanks ;) 
do you think it is better to add CORS headers in the <code>$headers</code> section of the <code>withArray(...)<code> method or to set them directly on Nginx?

**Comment by osteel** [comment]
@grcasanova I did not realise you needed CORS, I mentioned the article mainly for the installation steps of nginx-extras :)

Well like stated at the beginning of the blog post, if you are certain you will need all these headers for *every* request, it's probably better to set them in Nginx. But if you need specific rules for each route (allow different verbs for example), it's better to do it at an application level (so using `withArray` for example or a middleware - there are a few of them available for Laravel).
