### ISSUE TITLE
Possibility to pass headers to error responses

### ISSUE THREAD

**Issue by osteel** [ellipsesynergie/api-response#18]
Hi,

First of all thanks for this package, it's been very useful so far.

I'm using it with Lumen and I am facing a minor issue at the moment, as it is currently not possible to pass headers to the various shortcut methods for returning errors (`errorForbidden`, `errorNotFound`, etc).

In my case, authentification is handled using JWT, and the token is refreshed on every request and the new token is returned along with the response using a middleware.

When raising exceptions tho, the returned responses don't get through the middleware and the `Authorization` header (the one carrying the token) is not set.

This is where I would need to set it manually but the shortcuts methods won't allow me to do so.

This my own specific use case of course, but I believe some others could exist and I don't see anything wrong in adding an argument to these methods' signatures, as such:

`public function errorInternalError($message = 'Internal Error', $headers = [])`
`public function withError($message, $errorCode, $headers = [])`

Especially as `withArray` already accepts an array of headers as its second argument.

What do you think?

Thanks!

**Comment by maximebeaudoin** [comment]
@osteel I'm agree with that, but first i need to figure out if it's possible to make it work.

Related to this issue #17

**Comment by maximebeaudoin** [comment]
Resolved in #24
