### ISSUE TITLE
Error code references as "self" prevent extensibility 

### ISSUE THREAD

**Issue by saverio** [ellipsesynergie/api-response#25]
The error codes are defined as constants, which is great since they can be overridden by creating a class that extends Response; however, due to the fact that the constants are referenced via self::CODE_NOT_FOUND instead of static::CODE_NOT_FOUND, the constants being referenced are always the ones defined in the original class despite the class that was initiated.

**Comment by maximebeaudoin** [comment]
I'm agree with that. I'll take a look at it later this week. If you want, you create a new PR for this.
