### ISSUE TITLE
Return response from Laravel's Handler (now that api() macro is deprecated)

### ISSUE THREAD

**Issue by jonagoldman** [ellipsesynergie/api-response#28]
Now that the ```api()``` macro is deprecated, I want to know how to return a response from Laravel's exception handler (Exceptions/Handler).

In the past, I used something like this

```php
// inside the render() method in Handler.php

if ($e instanceof ApiException) {
    return response()->api()->withError($e->getMessage(), $e->getCode());
}
```

How can I avoid using ```api()``` ?

ps: sorry for not using the guidelines.

**Comment by maximebeaudoin** [comment]
@jonagoldman Personaly, in my Handler.php file i use the response object like this 

```php
$response = app(\EllipseSynergie\ApiResponse\Contracts\Response::class);

if ($e instanceof ValidatorException) {
    return response->errorWrongArgsValidator($e->errors());
};
```

**Comment by jonagoldman** [comment]
Thanks will try it out!
