### ISSUE TITLE
How to use HTTP status constants defined in Symfony\Component\HttpFoundation\Response?

### ISSUE THREAD

**Issue by artlivemediarepos** [ellipsesynergie/api-response#40]
How to use HTTP status constants(HTTP_UNAUTHORIZED etc) defined in Symfony\Component\HttpFoundation\Response without importing it in the controller as I am already using EllipseSynergie\ApiResponse\Contracts\Response? 

I'd like to do something like this `Response::HTTP_UNAUTHORIZED` with this package instead of 401? Could someone please guide if it is possible? Thanks!

**Comment by maximebeaudoin** [comment]
Hi, unfortunately you have to add the `symfony/http-foundation` as a dependancy if you want do that. We do not support HTTP status constants in this package because we also use `symfony/http-foundation` in our project and we don't want to force this dependency for everyone.
