### ISSUE TITLE
return json need $options

### ISSUE THREAD

**Issue by dickwu** [ellipsesynergie/api-response#43]
```PHP
/**
     * @param array $array
     * @param array $headers
     * @return ResponseFactory
     */
    public function withArray(array $array, array $headers = [],$options = 0)
    {
        return response()->json($array, $this->statusCode, $headers,$options);
    }
```
I need use `$options`  as  `JSON_UNESCAPED_UNICODE`
can you add it ?

**Comment by robertmain** [comment]
not really any of my business, but I'd suggest setting a default value on `$options` to be something other than zero....preferably `JSON_UNESCAPED_UNICODE` or some such

**Comment by maximebeaudoin** [comment]
@robertmain Currently, the default value from `Illuminate\Contracts\Routing\ResponseFactory` is 0. You can see the file https://github.com/laravel/framework/blob/5.5/src/Illuminate/Contracts/Routing/ResponseFactory.php#L37 so it's make sense to keep it that way.

@dickwu I think this is a really good idea. You create a PR for that if you want.

**Comment by robertmain** [comment]
@maximebeaudoin is that value available as a constant? I'm thinking it might make more semantic sense. Either way, just a thought :)

**Comment by dickwu** [comment]
@robertmain you can see this with more info [http://php.net/manual/en/function.json-encode.php](url)

**Comment by dickwu** [comment]
@maximebeaudoin I have already submitted it directly
