### ISSUE TITLE
Laravel 5 paginator class changed

### ISSUE THREAD

**Issue by etiennemarais** [ellipsesynergie/api-response#7]
Hi,

Seems like the `->withPaginator()` now receives a paginator of type `Illuminate\Pagination\LengthAwarePaginator` in L5 instead of the required `Illuminate\Pagination\Paginator`

Is there a workaround?

**Comment by maximebeaudoin** [comment]
@Av3ng3r Not until the L5 Beta or first release will be available. But this package will be compatible with L5 for sur.

**Comment by etiennemarais** [comment]
Hi, Thank you for the reply @maximebeaudoin . Will make a workaround till the upgrade for now.

**Comment by maximebeaudoin** [comment]
@etiennemarais The master branch now support Laravel 5. I'll wait until the `league/fractal` next release to tag the version 0.9.
